### ISSUE TITLE
update-quiz to update a quiz .

### ISSUE THREAD

**Issue by farah-najib** [Zocom-LIA/codecrafters-quizapp#2]
Update all quiz attributes""
- title
- description
- topic

**Comment by ioannismarkou** [comment]
![Image](https://github.com/user-attachments/assets/8f68ffac-9e3a-45c0-97e7-28c450a7cd80)

**Comment by ioannismarkou** [comment]
Update the question's attributes:

text
type
correct answer(s)

Update answer attrributes.
